require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CoursesController do

  # This should return the minimal set of attributes required to create a valid
  # Course. As you add validations to Course, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    context "anonymous user" do
      before(:each){logout}
      it "assigns all courses as @courses" do
        course = Course.create! valid_attributes
        get :index, {}
        assigns(:courses).should eq([course])
      end
    end

    context "normal user" do
      before(:each){login_user}
      it "assigns all courses as @courses" do
        course = Course.create! valid_attributes
        get :index, {}
        assigns(:courses).should eq([course])
      end
    end

    context "admin user" do
      before(:each){login_user}
      it "assigns all courses as @courses" do
        course = Course.create! valid_attributes
        get :index, {}
        assigns(:courses).should eq([course])
      end
    end
  end

  describe "GET show" do
    context "anonymous user" do
      before(:each){logout}
      it "assigns the requested course as @course" do
        course = Course.create! valid_attributes
        get :show, {:id => course.to_param}
        assigns(:course).should eq(course)
      end
    end

    context "normal user" do
      before(:each){login_user}
      it "assigns the requested course as @course" do
        course = Course.create! valid_attributes
        get :show, {:id => course.to_param}
        assigns(:course).should eq(course)
      end
    end

    context "admin user" do
      before(:each){login_admin}
      it "assigns the requested course as @course" do
        course = Course.create! valid_attributes
        get :show, {:id => course.to_param}
        assigns(:course).should eq(course)
      end
    end
  end

  describe "GET new" do
    context "anonymous user" do
      before(:each){logout}
      it "redirects to login page" do
        get :new, {}
        response.should redirect_to(new_user_session_path)
      end
    end

    context "normal user" do
      before(:each){login_user}
      it "redirects to login page" do
        get :new, {}
        response.should redirect_to(new_user_session_path)
      end
    end

    context "admin user" do
      before(:each){login_admin}
      it "assigns a new course as @course" do
        get :new, {}
        assigns(:course).should be_a_new(Course)
      end
    end
  end

  describe "GET edit" do
    context "anonymous user" do
      before(:each){logout}
      it "redirects to login page" do
        course = Course.create! valid_attributes
        get :edit, {:id => course.to_param}
        response.should redirect_to(new_user_session_path)
      end
    end

    context "normal user" do
      before(:each){login_user}
      it "redirects to login page" do
        course = Course.create! valid_attributes
        get :edit, {:id => course.to_param}
        response.should redirect_to(new_user_session_path)
      end
    end

    context "admin user" do
      before(:each){login_admin}
      it "assigns the requested course as @course" do
        course = Course.create! valid_attributes
        get :edit, {:id => course.to_param}
        assigns(:course).should eq(course)
      end
    end
  end

  describe "POST create" do
    context "anonymous user" do
      before(:each){logout}
      it "does not create a new course" do
        expect {
          post :create, {:course => valid_attributes}
        }.not_to change(Course, :count)
      end
      it "redirects to login page" do
        post :create, {:course => valid_attributes}
        response.should redirect_to(new_user_session_path)
      end
    end

    context "normal user" do
      before(:each){login_user}
      it "does not create a new course" do
        expect {
          post :create, {:course => valid_attributes}
        }.not_to change(Course, :count)
      end
      it "redirects to login page" do
        post :create, {:course => valid_attributes}
        response.should redirect_to(new_user_session_path)
      end
    end

    context "admin user" do
      before(:each){login_admin}
      describe "with valid params" do
        it "creates a new Course" do
          expect {
            post :create, {:course => valid_attributes}
          }.to change(Course, :count).by(1)
        end

        it "assigns a newly created course as @course" do
          post :create, {:course => valid_attributes}
          assigns(:course).should be_a(Course)
          assigns(:course).should be_persisted
        end

        it "redirects to the created course" do
          post :create, {:course => valid_attributes}
          response.should redirect_to(Course.last)
        end
      end

      describe "with invalid params" do
        it "assigns a newly created but unsaved course as @course" do
          # Trigger the behavior that occurs when invalid params are submitted
          Course.any_instance.stub(:save).and_return(false)
          post :create, {:course => {}}
          assigns(:course).should be_a_new(Course)
        end

        it "re-renders the 'new' template" do
          # Trigger the behavior that occurs when invalid params are submitted
          Course.any_instance.stub(:save).and_return(false)
          post :create, {:course => {}}
          response.should render_template("new")
        end
      end
    end
  end

  describe "PUT update" do
    context "anonymous user" do
      before(:each){logout}
      it "does not update the requested course" do
        course = Course.create! valid_attributes
        Course.any_instance.should_not_receive(:update_attributes)
        put :update, {:id => course.to_param, :course => valid_attributes}
      end
      it "redirects to login page" do
        course = Course.create! valid_attributes
        put :update, {:id => course.to_param, :course => valid_attributes}
        response.should redirect_to(new_user_session_path)
      end
    end

    context "normal user" do
      before(:each){login_user}
      it "does not update the requested course" do
        course = Course.create! valid_attributes
        Course.any_instance.should_not_receive(:update_attributes)
        put :update, {:id => course.to_param, :course => valid_attributes}
      end
      it "redirects to login page" do
        course = Course.create! valid_attributes
        put :update, {:id => course.to_param, :course => valid_attributes}
        response.should redirect_to(new_user_session_path)
      end
    end

    context "admin user" do
      before(:each){login_admin}

      describe "with valid params" do
        it "updates the requested course" do
          course = Course.create! valid_attributes
          # Assuming there are no other courses in the database, this
          # specifies that the Course created on the previous line
          # receives the :update_attributes message with whatever params are
          # submitted in the request.
          Course.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
          put :update, {:id => course.to_param, :course => {'these' => 'params'}}
        end

        it "assigns the requested course as @course" do
          course = Course.create! valid_attributes
          put :update, {:id => course.to_param, :course => valid_attributes}
          assigns(:course).should eq(course)
        end

        it "redirects to the course" do
          course = Course.create! valid_attributes
          put :update, {:id => course.to_param, :course => valid_attributes}
          response.should redirect_to(course)
        end
      end

      describe "with invalid params" do
        it "assigns the course as @course" do
          course = Course.create! valid_attributes
          # Trigger the behavior that occurs when invalid params are submitted
          Course.any_instance.stub(:save).and_return(false)
          put :update, {:id => course.to_param, :course => {}}
          assigns(:course).should eq(course)
        end

        it "re-renders the 'edit' template" do
          course = Course.create! valid_attributes
          # Trigger the behavior that occurs when invalid params are submitted
          Course.any_instance.stub(:save).and_return(false)
          put :update, {:id => course.to_param, :course => {}}
          response.should render_template("edit")
        end
      end
    end
  end

  describe "DELETE destroy" do
    context "anonymous user" do
      before(:each){logout}
      it "does not destroy the requested course" do
        course = Course.create! valid_attributes
        expect {
          delete :destroy, {:id => course.to_param}
        }.not_to change(Course, :count)
      end
      it "redirects to login page" do
        course = Course.create! valid_attributes
        delete :destroy, {:id => course.to_param}
        response.should redirect_to(new_user_session_path)
      end
    end

    context "normal user" do
      before(:each){login_user}
      it "does not destroy the requested course" do
        course = Course.create! valid_attributes
        expect {
          delete :destroy, {:id => course.to_param}
        }.not_to change(Course, :count)
      end
      it "redirects to login page" do
        course = Course.create! valid_attributes
        delete :destroy, {:id => course.to_param}
        response.should redirect_to(new_user_session_path)
      end
    end

    context "admin user" do
      before(:each){login_admin}

      it "destroys the requested course" do
        course = Course.create! valid_attributes
        expect {
          delete :destroy, {:id => course.to_param}
        }.to change(Course, :count).by(-1)
      end

      it "redirects to the courses list" do
        course = Course.create! valid_attributes
        delete :destroy, {:id => course.to_param}
        response.should redirect_to(courses_url)
      end
    end
  end

end
